name: Deploy MkDocs

on:
  push:
    branches:
      - disable

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material
        run: pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: mkdocs gh-deploy --force --verbose